### PR TITLE
Adding template and configuration item for JIRA Datacenter

### PR DESCRIPTION
**Pull request by ronaldvanrij**
Setting up a node for a JIRA datacenter requires this additional file to be created and specification of a shared location.

### CODE REVIEW

**Comment by igalic** [comment]
@ronaldvanrij this could use some documentation, perhaps some tests, too!

**Comment by ronaldvanrij** [comment]
Added tests and updated README.md

**Comment by igalic** [comment]
@ronaldvanrij this will need a rebase now

**Comment by ronaldvanrij** [comment]
@igalic rebase completed

**Comment by igalic** [comment]
thank you @ronaldvanrij!

**Pull request merged**
