### PR TITLE
Jira 7 Support

### PR DESCRIPTION
**Pull request by bramwelt**
Updates `server.xml` with JIRA 7's default settings and continues to support the installation and management of JIRA pre-7.

### CODE REVIEW

**Comment by bramwelt** [comment]
If there is a strong opinion that `jira` should default to `jira-core` and not `jira-software`, I'm happy to change it.

**Comment by igalic** [comment]
@bramwelt on a high-level view, this looks good to me.

ping @xtra-be @jared-di @Conzar @chihoko for review / test / feedback

**Comment by bramwelt** [comment]
@ffquintella I wouldn't have been able to write this change without seeing your work on #106 and #96! If you'd like credit, I'd be happy to update the author list on my changes.

**Comment by tobru** [comment]
I've just gave it a try and it seems to do what it should. So count my vote for a merge.

**Comment by igalic** [comment]
thanks y'all!
and thanks @bramwelt!

**Pull request merged**
